config/routes.rb
Salonsafari::Application.routes.draw do
  resources :photos
  get 'add_photo_to_folder' => 'photos#add_photo_to_folder'
  post 'add_photo_to_folder_post' => 'photos#add_photo_to_folder_post'

  get 'delete_photo_from_folder' => 'photos#delete_photo_from_folder'
  get 'delete_photo_from_folder_post' => 'photos#delete_photo_from_folder_post'

  get "welcome/index"
  get "about" => "welcome/about"
  get "service/affro" => "welcome#affro"
  get "service/chemicalperm" => "welcome#chemicalperm"
  get "contacts" => "welcome#contacts"
  get "gallery" => "welcome#gallery"
  get "service/haircare" => "welcome#haircare"
  get "service/haircoloring" => "welcome#haircoloring"
  get "service/haircut" => "welcome#haircut"
  get "service/hairextension" => "welcome#hairextension"
  get "service/hairstyling" => "welcome#hairstyling"
  get "service/makeup" => "welcome#makeup"
  get "service/manicure" => "welcome#manicure"
  get "service" => "welcome#service"
  resources :users

  resources :comments
  
  resources :vacancies

  resources :sales

  resources :news

  get 'admin' => 'admin#index'
  get 'admin/index_post'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  root to: 'welcome#index', as: 'index'








end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  skip_before_action :authorize, only: [:index]
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  require 'securerandom'

  # GET /news
  # GET /news.json
  def index
  
	# Get all news ordered by added date
	# paginate method is used to split all news by pages with 3 notes
    @news = News.order('created_at desc').paginate(:page => params[:page], :per_page => 3)
    @users = User.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
    # Get all users from database
    @users = User.all

	# If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # GET /news/new
  def new
    # Get all news form database
    @news = News.new
	
	# Get all users from database
    @users = User.all

	# If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # GET /news/1/edit
  def edit
   # Get all users from database
    @users = User.all

	# If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # POST /news
  # POST /news.json
  def create
    # Get all users from database
    @users = User.all

	# If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
	
	# Create news with params
    @news = News.new(news_params)

	# Get uploaded file path
    uploaded_file = @news.image_path

	# Get file name of uploaded image
    filename = @news.image_path.original_filename
	
	# Set path to image of created news to recieved file name
    @news.image_path = filename

	# Get type of file
    content_type = uploaded_file.content_type
	
	# Get bytes of uploaded file
    data = uploaded_file.read
	
	# Save file to app/assets/images directory with original file name
    File.open(Rails.root.join('app', 'assets', 'images', filename), 'wb') do|f|
        f.write(data)
    end

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_url, notice: 'News was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    # Get all users from database
    @users = User.all

	# If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
	
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_index_url, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
	# Get all users from database
    @users = User.all

	# If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end

    File.delete(Rails.root.join('app', 'assets', 'images', @news.image_path))
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :description, :image_path)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for @news, :html => { :id => "form-horizontal"} do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="col-sm-2 control-label">Заголовок</label>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" style="margin-top: 10px;">Описание</label>
    <div class="col-sm-10" style="margin-top: 10px;">
      <%= f.text_area :description, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" style="margin-top: 10px;">Изображение</label>
    <div class="col-sm-10" style="margin-top: 10px;">
      <%= f.file_field :image_path%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10" style="margin-top: 10px;">
      <%= f.submit 'Отправить', :class => 'btn btn-warning'%>
    </div>
  </div>
<% end %>

app/views/news/edit.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Новости
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
		    <li><a href="<%= news_index_path %>"><strong>Новости</strong></a>
                    </li>
                    <li class="active">Изменение новости</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Измените новость:</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/news/index.html.erb
<% if session[:user_id] %>
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				Новости
			</h1>
			<ol class="breadcrumb">
		            <li><a href="<%= index_path %>"><strong>Главная</strong></a>
		            </li>
		            <li class="active">Новости</li>
		        </ol>
		</div>
	</div>
	<!-- /.row -->

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Текущие новости</div>
		<div class="panel-body">
			<a href="<%= new_news_path %>" class="btn btn-warning">Добавить новость</a>
		</div>

		<table class="table table-hover">
			<% @news.each do |news| %>
			      <tr>
				<td><%= news.title %></td>
				<td><%= news.description.gsub(/\n/, '<br/>').html_safe %></td>
				<td><%= link_to 'Удалить', news, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить эту запись?' } %></td>
			      </tr>
			<% end %>
		</table>
		<div align="center"><%= will_paginate @comments %></div>
	</div>
<% else %>	
		<div class="row">
		    <div class="col-lg-12">
		        <h1 class="page-header">Новости
		        </h1>
		        <ol class="breadcrumb">
		            <li><a href="<%= index_path %>">Главная</a>
		            </li>
		            <li class="active">Новости</li>
		        </ol>
		    </div>
		</div>
		<!-- /.row -->

		<% @news.each do |news| %>
		<div class="alert alert-warning" id="<%= news.id %>" role="alert">Запись добавлена <%= news.created_at %></div>
		<!-- Blog Post Row -->
		<div class="row">
		    <div class="col-md-5">
		        <a>
		            <img class="img-responsive img-hover" src="<%= image_url news.image_path %>" alt="">
		        </a>
		    </div>
		    <div class="col-md-6">
		        <h3>
		            <a><%= news.title %></a>
		        </h3>
		        <p>by <a>Elena Nikitina</a>
		        </p>
		        <p><%= news.description.gsub(/\n/, '<br/>').html_safe %></p>
		        <a id="<%= news.id %>" onclick="show_hide_ref(this.id)" class="btn btn-warning" style="margin-bottom: 10px;">Получить ссылку</a>
			<br>
			<input type="text" class="form-control" id="input<%= news.id %>" style="display: none" value="<%= request.original_url %>#<%= news.id %>">
		    </div>
		</div>
		<!-- /.row -->

		<hr>
	<% end %>
	<div align="center"><%= will_paginate @comments %></div>
<% end %>
<% if @news.count == 0 and !session[:user_id] %>
	<div class="alert alert-warning" role="alert">Новостей пока нет! Но не расстраивайтесь, скоро появятся :)</div>
<% end %>

<script>
function show_hide_ref(id){
	$('#input'+id).toggle();
}
</script>

app/views/news/new.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Новости
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
		    <li><a href="<%= news_index_path %>"><strong>Новости</strong></a>
                    </li>
                    <li class="active">Добавление новости</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Добавьте новость:</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>

<p>
  <strong>Image path:</strong>
  <%= @news.image_path %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>