config/routes.rb
Salonsafari::Application.routes.draw do
  resources :photos
  get 'add_photo_to_folder' => 'photos#add_photo_to_folder'
  post 'add_photo_to_folder_post' => 'photos#add_photo_to_folder_post'

  get 'delete_photo_from_folder' => 'photos#delete_photo_from_folder'
  get 'delete_photo_from_folder_post' => 'photos#delete_photo_from_folder_post'

  get "welcome/index"
  get "about" => "welcome/about"
  get "service/affro" => "welcome#affro"
  get "service/chemicalperm" => "welcome#chemicalperm"
  get "contacts" => "welcome#contacts"
  get "gallery" => "welcome#gallery"
  get "service/haircare" => "welcome#haircare"
  get "service/haircoloring" => "welcome#haircoloring"
  get "service/haircut" => "welcome#haircut"
  get "service/hairextension" => "welcome#hairextension"
  get "service/hairstyling" => "welcome#hairstyling"
  get "service/makeup" => "welcome#makeup"
  get "service/manicure" => "welcome#manicure"
  get "service" => "welcome#service"
  resources :users

  resources :comments
  
  resources :vacancies

  resources :sales

  resources :news

  get 'admin' => 'admin#index'
  get 'admin/index_post'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  root to: 'welcome#index', as: 'index'








end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  require 'fileutils'
  skip_before_action :authorize, only: [:index, :show]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
  
	# Get all users form databse
    @users = User.all
	
	# Get all photos from database
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  
	# Get all users form databse
    @users = User.all
  end

  # GET /photos/new
  def new
  
	# Get all users form databse
    @users = User.all
	
	# Create new photo
    @photo = Photo.new

    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # GET /photos/1/edit
  def edit
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # POST /photos
  # POST /photos.json
  def create
  
	# Get all users form databse
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
	
	# Create new photo
    @photo = Photo.new(photo_params)

	# Get full path to app/assets/images/<name of current photo album> directory 
    path_to_dir = Rails.root.join('app', 'assets', 'images', @photo.name)    

	# Create directory with path_to_dir path
    FileUtils::mkdir_p path_to_dir

	# Get uploaded cover image
    uploaded_cover = @photo.cover

	# Get file name of uploaded image
    filename_cover = @photo.cover.original_filename
	
	# Set cover image to recieved file name
    @photo.cover = filename_cover

	# Get bytes of uploaded image
    data = uploaded_cover.read

	# Save file to app/assets/images/<name of current photo album> directory with original file name of cover
    File.open(Rails.root.join('app', 'assets', 'images', @photo.name, filename_cover), 'wb') do|f|
        f.write(data)
    end

    paths = "" # Variable that store paths to uploaded images
	
	# If uploaded files are not null (nil)
    if !params[ :files ].nil?

		# For each uploaded files
    	params[ :files ].each{ |file|
		
			# Get file name of uploaded image
			filename = file.original_filename
			
			# Concateate current path value with new path - recieved filename and ";" symbol to separate paths
    	    paths = paths + filename + ";"
			
			# Save recieved image to app/assets/images/<name of current photo album> directory with original file name of image
			File.open(Rails.root.join('app', 'assets', 'images', @photo.name, filename), 'wb') do|f|
				f.write(file.read)
			end
    	}
    end
  
   @photo.image_paths = paths[0...-1]

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_url, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
	
	# Get all users form databse
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end

    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photos_url, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    # Get all users form databse
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end

	# Get all paths to images into this photo album
    photo_paths = @photo.image_paths.split(';')
	
	# For each image in album
    photo_paths.each{ |path_to_image|
	
		# Delete current image by filename from app/assets/images/<name of current photo album> directory
		File.delete(Rails.root.join('app', 'assets', 'images', @photo.name, path_to_image))
    }

	# Delete cover image
    File.delete(Rails.root.join('app', 'assets', 'images', @photo.name, @photo.cover))

	# Delete directory of current photo album
    FileUtils.rm_rf(Rails.root.join('app', 'assets', 'images', @photo.name))

    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  # Get method
  def add_photo_to_folder
  
	# Get current url
    url = request.original_url

	# Create new photo album
    @photo = Photo.new
   
	# Set photo_id in session as the symbol that locate after the last point in url
    session[:photo_id] = url.split('.').last()

	# Find photo album by calculated id
    photo = Photo.find_by(id: session[:photo_id])

    @id_photo = url.split('.').last()
	
  end
  
  # Post method
  def add_photo_to_folder_post

	# Find photo album by id in the session variable
    photo = Photo.find_by(id: session[:photo_id])

    # Get path to app/assets/images/<name of current photo album> directory
    path_to_folder = Rails.root.join('app', 'assets', 'images', photo.name)

	# Get all files from directory
    records = Dir.glob(path_to_folder.to_s + "/**/*" )

	# Memorize all photos in the album
    old_photos = photo.image_paths
    
    paths = "" # Variable that store paths to uploaded images
	
	# If uploaded files are not null (nil)
    if !params[ :files ].nil?
	
		# For each file
    	params[ :files ].each{ |file|
		
			# Get file name of uploaded image
			filename = file.original_filename
			
			# Get path to file that we want to add to album
			path_to_adding_file = Rails.root.join('app', 'assets', 'images', photo.name, filename).to_s
	     
			is_found = false # Flag tha indicates if file name was found
			
			# Get random value from 0 to 199 and transform it to string
			added_value = rand(0..199).to_s

			# For each file from directory of current photo album
			records.each { |exist_file|

				# If file with current file name allready exist in album
				if exist_file == path_to_adding_file
				
					# Set flag to true
					is_found = true
					
					# Generate new random value
					added_value = rand(0..199).to_s
					
					# While original file name not found
					while exist_file == Rails.root.join('app', 'assets', 'images', photo.name, added_value + '_' + filename).to_s
					
						# Generate new random value
						added_value = rand(0..199).to_s
					end
				end
			}
	     
			# If file is found
			if is_found
				
				# Set current file name to random value (integer) + '_' sybmol and + current file name
             	filename = added_value + '_' + filename
			end

			# If file name contains symbol "."
			if filename.to_s.include? "."
			
				# Then add current file name to paths variable (concatenate)
    	     	paths = paths + filename + ";"
			end

			# Write image to directory
			File.open(Rails.root.join('app', 'assets', 'images', photo.name, filename), 'wb') do|f|
				f.write(file.read)
			end
    	 }
    end

	# Concatenate memorized images in album with new images (except the last value of paths variable)
    photo.image_paths = old_photos + ";" + paths[0...-1]

	# Check if array still contains equal values
	
    is_bad = false # Flag that indicates if the array contains equal values
	
	# Get all images paths
    mass = photo.image_paths.split(';')
	
	# Create new array that contains just uniq values of old array
    new_array = mass.uniq
	
	# If th lengths of old and new array is not equal
    if mass.length != new_array.length
	
		# Set the flag value to true - array contains equal values
		is_bad = true
    end
    
	# If array contains just uniq values
    if !is_bad
	
		# Save photo album to database
    	photo.save
    else
		redirect_to comments_path_url
    end

    session[:photo_id] = -1
   
    redirect_to photos_url

  end

  # Get method
  def delete_photo_from_folder
  
	# Get current url
	url = request.original_url
	  
	# Set photo_id in session as the symbol that locate after the last point in url
	session[:photo_id] = url.split('.').last()
	
	# Find photo album by calculated id
	photo = Photo.find_by(id: session[:photo_id])
	
	# Get name of curretn photo album
	@photo_name = photo.name

	# Get all photos in album
	@list_of_photo = photo.image_paths.split(';')
	
  end

  # Post method
  def delete_photo_from_folder_post
	
	# Get current url
	url = request.original_url
	  
	# Get id of current photo
	i = url.split('.').last().to_i
	
	# Find photo album by calculated id
	photo = Photo.find_by(id: session[:photo_id])
	
	# Get all photos in album
	list_of_photos = photo.image_paths.split(';')

	# Get image by id (index of image in array)
	element = list_of_photos[i]
	
	# Delet file from app/assets/images/<name of current photo album> directory and recieved file name
	File.delete(Rails.root.join('app', 'assets', 'images', photo.name, element))	
	
	# Delete current photo from list of photo images
	list_of_photos.delete(element)

	# Update paths varibale to save it to database
	paths = ""
	list_of_photos.each { |item|
		paths = paths + item + ";"
	}

	# Iamges of current photo album is equal to paths variable except the last element
	photo.image_paths = paths[0...-1]

	# Save photo album to database
	photo.save

	redirect_to photos_url
	
  end

  private

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, html: { multipart: true, :id => "form-horizontal" }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <label class="col-sm-2 control-label">Название</label>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" style="margin-top: 10px;">Описание</label>
    <div class="col-sm-10" style="margin-top: 10px;">
      <%= f.text_area :description, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" style="margin-top: 10px;">Изображение (можно выбрать несколько)</label>
    <div class="col-sm-10" style="margin-top: 10px;">
      <%= file_field_tag 'files[]', :multiple => true %>
    </div>
  </div>
  <br clear="all">
  <div class="form-group">
    <label class="col-sm-2 control-label" style="margin-top: 10px;">Обложка для папки (допускается загрузка ТОЛЬКО изображений с размером 600х450 )</label>
    <div class="col-sm-10" style="margin-top: 10px;">
      <%= f.file_field :cover %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10" style="margin-top: 10px;">
      <%= f.submit 'Отправить', :class => 'btn btn-warning'%>
    </div>
  </div>
<% end %>

app/views/photos/add_photo_to_folder.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Добавление фотографий к папке
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
		    <li><a href="<%= photos_path %>"><strong>Фотогалерея</strong></a>
                    </li>
                    <li class="active">Добавление фотографий...</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Добавление фото к папке  <%= @records %>:</div>
	<div class="panel-body">
		<%= form_for(@photo, :url => add_photo_to_folder_post_path, html: { multipart: true, :id => "contact-form" }) do |f| %>
			  <div class="form-group">
			    <label class="col-sm-2 control-label" style="margin-top: 10px;">Изображение (можно выбрать несколько)</label>
			    <div class="col-sm-10" style="margin-top: 10px;">
			      <%= file_field_tag 'files[]', :multiple => true %>
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10" style="margin-top: 10px;">
			      <%= f.submit 'Отправить', :class => 'btn btn-warning'%>
			    </div>
			  </div>
		<% end %>
	</div>
</div>

app/views/photos/add_photo_to_folder_post.html.erb
HELLO

app/views/photos/delete_photo_from_folder.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Удаление фотографий из папки
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
		    <li><a href="<%= photos_path %>"><strong>Фотогалерея</strong></a>
                    </li>
                    <li class="active">Удаление фотографий</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Удалите необходимые фотографии:</div>
	<div class="panel-body">
		<table class="table">
			<% i = 0 %>
			    <% @list_of_photo.each do |photo| %>
			      <tr>
				<td><img src="<%= image_url(@photo_name + '/' +  photo) %>" alt="" width="200" height="200"></td>
				<td><%= photo %></td>
				<td><%= link_to 'Удалить фото', delete_photo_from_folder_post_path(i), :class => "btn" %></td>
			      </tr>
			      <% i = i + 1 %>
			    <% end %>
		</table>
	</div>
</div>

app/views/photos/delete_photo_from_folder_post.html.erb
HELLO

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Галерея
		</h1>
	</div>
</div>

<% if session[:user_id] %>
<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Добавленные папки:</div>
	<div class="panel-body">
		
	<a href="<%= new_photo_path %>" class="btn btn-warning">Добавить новую папку</a>
	</div>
		<table class="table table-hover">
		  <% @photos.each do |photo| %>
		      <tr>
			<td><%= photo.name %></td>
			<td><%= photo.description %></td>
		        <td><%= link_to 'Добавить фото', add_photo_to_folder_path(photo.id) %></td>
			<td><%= link_to 'Удалить фото из папки', delete_photo_from_folder_path(photo.id) %></td>
			<td><%= link_to 'Удалить', photo, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить эту запись?' } %></td>
		      </tr>
		    <% end %>
		</table>
</div>
<% else %>
	<div class="row">
	<% @photos.each do |photo| %>
		<div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <%= link_to image_tag(photo.name + "/" + photo.cover), photo %>
		      <div class="caption">
			<h3><%= photo.name %></h3>
			<p><%= photo.description %></p>
			<p><%= link_to 'Открыть', photo, :class => "btn btn-warning" %></p>
		      </div>
		    </div>
		  </div>
	<% end %>
	</div>

<% end %>
<% if @photos.count == 0 %>
	<div class="panel panel-warning">
		<div class="panel-heading">Фотогалерея пока пуста</div>
		<div class="panel-body">
		    <p>Но это не значит, что нам нечего Вам показать. Вы можете найти фотографии в наших группах в социальных сетях:</p>
		    <p>
			<a href="http://vk.com/salon_safari" target="_blank">
				<img src="<%= image_url 'vk.png' %>" height="40" width="40"/>
			</a>
			<a href="https://www.instagram.com/salonsafari/" target="_blank">
				<img src="<%= image_url 'instagram.png' %>" height="40" width="40"/>
			</a>
			<a href="https://ok.ru/group/50839877320795" target="_blank">
				<img src="<%= image_url 'ok.png' %>" height="40" width="40"/>
			</a>
		    </p>
		</div>
	</div>
<% end %>

app/views/photos/new.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Фотогалерея
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
		    <li><a href="<%= photos_path %>"><strong>Фотогалерея</strong></a>
                    </li>
                    <li class="active">Новая папка</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Добавьте новую папку:</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/photos/show.html.erb
<% photos_in_folder = @photo.image_paths.split(';') %>

<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			<%= @photo.name %>
		</h1>
	</div>
</div>

<div class="row">
	<% photos_in_folder.each do |photo| %>
	<div class="col-xs-6 col-md-3">
		<a class="thumbnail">
			<img src="<%= image_url(@photo.name + '/' +  photo) %>" alt="...">
		</a>
	</div>
	<% end %>
</div>