config/routes.rb
Salonsafari::Application.routes.draw do
  resources :photos
  get 'add_photo_to_folder' => 'photos#add_photo_to_folder'
  post 'add_photo_to_folder_post' => 'photos#add_photo_to_folder_post'

  get 'delete_photo_from_folder' => 'photos#delete_photo_from_folder'
  get 'delete_photo_from_folder_post' => 'photos#delete_photo_from_folder_post'

  get "welcome/index"
  get "about" => "welcome/about"
  get "service/affro" => "welcome#affro"
  get "service/chemicalperm" => "welcome#chemicalperm"
  get "contacts" => "welcome#contacts"
  get "gallery" => "welcome#gallery"
  get "service/haircare" => "welcome#haircare"
  get "service/haircoloring" => "welcome#haircoloring"
  get "service/haircut" => "welcome#haircut"
  get "service/hairextension" => "welcome#hairextension"
  get "service/hairstyling" => "welcome#hairstyling"
  get "service/makeup" => "welcome#makeup"
  get "service/manicure" => "welcome#manicure"
  get "service" => "welcome#service"
  resources :users

  resources :comments
  
  resources :vacancies

  resources :sales

  resources :news

  get 'admin' => 'admin#index'
  get 'admin/index_post'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  root to: 'welcome#index', as: 'index'








end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  skip_before_action :authorize, only: [:index]
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
  
	# Get all users from database
    @users = User.all
	
	# Get all sales from database
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
	# Get all users form databse
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # GET /sales/new
  def new
    # Get all users form databse
    @users = User.all
	
	# Get all sales from database
    @sales = Sale.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # GET /sales/1/edit
  def edit
   # Get all users form databse
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
  end

  # POST /sales
  # POST /sales.json
  def create
   # Get all users form databse
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end
	
	# Create new sale
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_url, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    # Get all users form database
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end

    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sales_url, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    # Get all users form databse
    @users = User.all
	
    # If user not authorized
    if !session[:user_id]
		
		# Then redirect user to Index page
		redirect_to index_url
    end

	# Delete current sale from database
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:title, :description)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale, :html => { :id => "form-horizontal"} do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <label class="col-sm-2 control-label">Заголовок</label>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" style="margin-top: 10px;">Описание</label>
    <div class="col-sm-10" style="margin-top: 10px;">
      <%= f.text_area :description, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10" style="margin-top: 10px;">
      <%= f.submit 'Отправить', :class => 'btn btn-warning'%>
    </div>
  </div>
<% end %>

app/views/sales/edit.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Акции
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
		    <li><a href="<%= sales_path %>"><strong>Акции</strong></a>
                    </li>
                    <li class="active">Изменение акции</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Измените акцию:</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/sales/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Акции
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
                    <li class="active">Акции</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<% if session[:user_id] %>
<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Текущие акции</div>
	<div class="panel-body">
		
			<a href="<%= new_sale_path %>" class="btn btn-warning">Добавить акцию</a>
	</div>
		<table class="table table-hover">
		  <% @sales.each do |sale| %>
		      <tr>
			<td><%= sale.title %></td>
			<td><%= sale.description %></td>
			<td><%= link_to 'Изменить', edit_sale_path(sale) %></td>
			<td><%= link_to 'Удалить', sale, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить эту запись?' } %></td>
		      </tr>
		    <% end %>
		</table>
</div>
<% else %>
	<% @sales.each do |sale| %>
			<div class="panel panel-warning">
			  <div class="panel-heading">
			    <h3 class="panel-title"><%= sale.title %></h3>
			  </div>
			  <div class="panel-body">
			   	<%= sale.description %>
			  </div>
			</div>
	<% end %>
<% end %>
<% if @sales.count == 0 %>
			<div class="alert alert-warning" role="alert">
				Акций нет! Но вы можете уточнить наличие специальных предложений по телефону - 8 937 714 65 56
			</div>
<% end %>

app/views/sales/new.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Акции
		</h1>
		<ol class="breadcrumb">
                    <li><a href="<%= index_path %>"><strong>Главная</strong></a>
                    </li>
		    <li><a href="<%= sales_path %>"><strong>Акции</strong></a>
                    </li>
                    <li class="active">Новая акция</li>
                </ol>
	</div>
</div>
<!-- /.row -->

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Добавьте новую акцию:</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sale.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sale.description %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>